language: php

php:
  - 5.6
  - 7.0
  - 7.0
  - 7.1

dist: trusty

env:
  matrix:
    - DB=mysql db_dsn='mysql://root:@127.0.0.1/quick_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: PHPCS=1

before_install:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE quick_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE quick_test_install;'; fi"
  - phpenv rehash
  - set +H

before_script:
  - COMPOSER_ROOT_VERSION=dev-master
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p -n --ignore=*/Lib/*,*fixture/*,*webroot/*,*config/*,*aop/* --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./plugins; fi"

notifications:
  email: false
